#!/bin/sh
exec 2>&1

MQTT_BROKER="127.0.0.1"
BATTERIES="4"

cd /data/dbus-mqtt-battery
exec python3 dbus-mqtt-battery.py \
    --broker "$MQTT_BROKER" \
    --batteries "$BATTERIES" \
    --instance 512 \
    --topic-prefix battery \
    --service-suffix mqtt_chain1 \
    --product-name "JBD Battery Chain 1"
